# Generated by Django 3.2.19 on 2023-05-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
