# Generated by Django 3.2.19 on 2023-05-23 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0002_alter_useractivity_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='user',
        ),
    ]
