# Generated by Django 3.2.19 on 2023-05-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0003_remove_useractivity_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
