# Generated by Django 3.2.19 on 2023-05-25 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0004_useractivity_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='order',
        ),
    ]
