# Generated by Django 3.2.19 on 2023-05-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0005_remove_useractivity_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='page_type',
            field=models.CharField(blank=True, choices=[('HT', 'Hits'), ('DP', 'Drop')], max_length=2, null=True),
        ),
    ]
