# Generated by Django 3.2.19 on 2023-05-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0007_alter_useractivity_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='page_type',
            field=models.CharField(blank=True, choices=[('HIT', 'Hit'), ('SURF', 'Surf'), ('EXIT', 'Exit')], max_length=10, null=True),
        ),
    ]
