# Generated by Django 3.2.19 on 2023-05-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0008_alter_useractivity_page_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserActivity',
            new_name='VisitorActivity',
        ),
    ]
