# Generated by Django 3.2.19 on 2023-06-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0010_auto_20230605_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitoractivity',
            name='mac_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visitoractivity',
            name='path_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
