# Generated by Django 3.2.19 on 2023-06-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0011_auto_20230619_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitoractivity',
            name='path_name',
        ),
    ]
